### ISSUE TITLE
Add a resources page

### ISSUE THREAD

**Issue by mblayman** [python-frederick/python-frederick.github.io#16]
The home page could link to the resources page in the "Open Workshops" description and a top nav link to "GET HELP"

The copy on the page should be more than a list of resources. It should welcome and guide new visitors assuming that they know nothing about coding (remember: the site's tagline is "Ready to learn to code?"). It *can* contain a list of resources, but that should be after a solid introduction.

**Comment by appiboat** [comment]
https://www.tutorialspoint.com/python_online_training/index.asp.

This has both videos and text. Was written with earlier version so print is print"  " instead of print(" ")but gives pretty much good information.

**Comment by appiboat** [comment]
Another book resource is Automate the boring stuff. Practical programming for total beginners by Al Sweigart. 

Chapter 13 talks about working with pdf and word. I guess the lady who wanted to know something about python and pdf document can look at that section if it helps.

**Comment by appiboat** [comment]
Sorry Automate the boring stuff with python is the book title.

**Comment by mblayman** [comment]
We had a quite a few young people at the workshop today. I got Python installed on their machine, but I didn't have great suggestions for what they could do next. It would be nice to have resources specifically aimed at teens/high school students.

**Comment by mblayman** [comment]
Maybe PyCharm Edu?

**Comment by mblayman** [comment]
Maybe Exercism.io

**Comment by mblayman** [comment]
Maybe Mu for beginners

**Comment by mblayman** [comment]
From @butterfly13

- https://www.youtube.com/watch?v=Z1Yd7upQsXY&list=PLBZBJbE_rGRWeh5mIBhD-hhDwSEDxogDg 
- https://www.learnpython.org/
- https://www.makeuseof.com/tag/basic-python-examples-learn-fast/
- https://realpython.com/python-beginner-tips/

**Comment by mblayman** [comment]
I think there is a good starting set now.
